# Generated by Django 5.0.7 on 2024-07-17 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recording',
            old_name='recording',
            new_name='audio_file',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.AddField(
            model_name='recording',
            name='text_field',
            field=models.TextField(blank=True, null=True),
        ),
    ]
